### ISSUE TITLE
Club card grid is not centered

### ISSUE THREAD

**Issue by MichaelZhao21** [MichaelZhao21/tams-club-cal#116]
The `display: grid` formatting is currently (in `client/src/pages/Clubs.scss`):

```scss
.club-card-list {
    padding: 1.25rem 7rem 1rem;
    display: grid;
    grid-template-columns: repeat(auto-fill, 9rem);
    row-gap: 1rem;
    justify-content: start;
}
```

This allows for overflow and mobile compatibility, but it doesn't center itself :((
