### ISSUE TITLE
Active Menu items still show dotted outline

### ISSUE THREAD

**Issue by MichaelZhao21** [MichaelZhao21/tams-club-cal#64]
In `Menu.scss`, the lines

```scss
.menu-item:active {
    outline: none;
}
```

should be changed to 

```scss
.menu-item:focus {
    outline: none;
}
```
